name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # add step to run npm install
    - name: Install dependencies
      run: npm install
    - name: docker login
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: romitsutariya/node_redis
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
